{{- if and .Values.auth.tokens (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcs.fullname" . }}-tokens
  labels:
    {{- include "mcs.labels" . | nindent 4 }}
type: Opaque
stringData:
  MCS_TOKENS: {{ .Values.auth.tokens | quote }}
{{- end }}
